#!/usr/bin/env python3
"""Generate the two data files the public site needs, from the repo's own source of truth.

    site/assets/dict.json   碼 → 候選字（線上試打用）
    site/assets/t2s.json    繁 → 簡 單字對照（繁簡切換用）

Both outputs are **generated, never hand-edited, and gitignored**. They are rebuilt in the
Pages workflow right before deploy, so the published demo can never drift from `data/codes.json`
the way a committed copy would — every newly coded character is live the next time the site
deploys.

Run it by hand before previewing locally:

    python3 site/tools/build_site_data.py

Reading Side A's data is fine from any side (the guard never blocks reads). Writing stays inside
`site/`, which is Side C's. This script must not write anywhere else.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DATA = ROOT / "data"
OUT = ROOT / "site" / "assets"


def shorten(code, rule):
    """Must stay identical to build_rime.py:36 — the demo is a lie if it disagrees with the IME."""
    if not rule:
        return code
    p = rule.get("params", {})
    mx, head, tail = p.get("max", 5), p.get("head", 4), p.get("tail", 1)
    if len(code) <= mx:
        return code
    return code[:head] + (code[-tail:] if tail else "")


def load(name):
    path = DATA / name
    if not path.exists():
        sys.exit(f"missing {path} — run this from a full checkout")
    return json.loads(path.read_text("utf-8"))


def main():
    codes = load("codes.json")
    rules = load("rules.json")
    freq_order = load("freq.json").get("order", [])
    t2s_raw = load("opencc.json").get("t2s", {})

    max_rule = next((r for r in rules.get("rules", [])
                     if r["id"] == "max_code_length" and r.get("enabled")), None)

    # 字頻決定候選順序，跟 IME 的候選列一致；沒進字頻表的字排最後、彼此照碼表順序。
    rank = {c: i for i, c in enumerate(freq_order)}
    far = len(rank) + 1

    table = {}          # code(lower) -> [chars]

    def add(code, ch):
        if not code:
            return
        bucket = table.setdefault(code.lower(), [])
        if ch not in bucket:
            bucket.append(ch)

    for ch, rec in codes.items():
        full = rec.get("code")
        if not full:
            continue
        # display：makemeahanzi 偶爾把字形畫成別的通行體（為 → 爲），碼表輸出的是那個字形。
        out = rec.get("display") or ch
        add(shorten(full, max_rule), out)       # 主碼：實際要按的
        add(full, out)                          # 完整碼：拆完每一碼也一律接受
        for alt in rec.get("alts", []):         # 兼容碼：手動收的另一條路（連它的完整碼）
            ac = alt.get("code")
            if ac:
                add(shorten(ac, max_rule), out)
                add(ac, out)

    for bucket in table.values():
        bucket.sort(key=lambda c: rank.get(c, far))

    # 約定簡碼：60 個手挑的常用字。這是網站要示範的核心設計，所以一起輸出。
    short, short_rev = {}, {}
    sc = next((r for r in rules.get("rules", []) if r["id"] == "short_code"), None)
    if sc:
        for e in (sc.get("params", {}).get("entries") or sc.get("entries") or []):
            ch, s = e.get("c"), (e.get("short") or "").lower()
            if not ch or not s or ch not in codes:
                continue
            short.setdefault(s, ch)             # 撞碼時第一個贏，與 rules 頁預覽一致
            short_rev.setdefault(ch, s)

    # 官方字表覆蓋率：網站首頁的數字由這裡算，不手抄。手抄的數字每次取碼都會過期，
    # 而過期的進度數字在對外網站上比沒有數字更糟。
    stats = {"chars": len(codes)}
    for sid, label, fname in [("tw4808", "教育部常用國字", "tw_common_4808.txt"),
                              ("gb2312", "GB 2312", "gb2312.txt")]:
        path = DATA / "standards" / fname
        if not path.exists():
            continue
        chars = {c for line in path.read_text("utf-8").splitlines()
                 if not line.startswith("#") for c in line.strip()}
        done = len(chars & set(codes))
        stats[sid] = {"label": label, "done": done, "total": len(chars),
                      "pct": round(done * 100 / len(chars), 1)}

    # 重碼率：首 2000 常用字裡，有多少字跟別的字共用同一個主碼。這是對外會被引用的數字，
    # 所以定義寫死在這裡、每次重算 —— 「涉及重碼的字 ÷ 2000」，跟文案講的是同一件事。
    top = [c for c in freq_order if c in codes][:2000]
    groups = {}
    for ch in top:
        groups.setdefault(shorten(codes[ch]["code"], max_rule), []).append(ch)
    clashed = sum(len(v) for v in groups.values() if len(v) > 1)
    if top:
        stats["clash"] = {"pool": len(top), "chars": clashed,
                          "pct": round(clashed * 100 / len(top), 1)}

    dict_out = {
        "note": "generated by site/tools/build_site_data.py — do not edit",
        "chars": len(codes),
        "stats": stats,
        "codes": {k: "".join(v) for k, v in sorted(table.items())},
        "short": short,
        "short_rev": short_rev,
        "short_enabled": bool(sc and sc.get("enabled")),
    }

    # 值是候選陣列，取第一個（標準簡化字）；51 個多候選字的其餘寫法用不到。
    t2s = {k: (v[0] if isinstance(v, list) else v) for k, v in t2s_raw.items()}
    t2s = {k: v for k, v in t2s.items() if k != v}

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "dict.json").write_text(
        json.dumps(dict_out, ensure_ascii=False, separators=(",", ":")), "utf-8")
    (OUT / "t2s.json").write_text(
        json.dumps(t2s, ensure_ascii=False, separators=(",", ":")), "utf-8")

    print(f"dict.json  {len(dict_out['codes'])} 碼 / {len(codes)} 字 / {len(short)} 簡碼")
    print(f"t2s.json   {len(t2s)} 組繁簡對照")


if __name__ == "__main__":
    main()
