#!/usr/bin/env python3
"""Generate the data files the public site needs, from the repo's own source of truth.

    site/assets/dict.json   碼 → 候選字（線上試打用）
    site/assets/t2s.json    繁 → 簡 單字對照（繁簡切換用）
    site/assets/zigen.json  字根表（取形意圖 ＋ 例字），給 zigen.html 用

All outputs are **generated, never hand-edited, and gitignored**. They are rebuilt in the
Pages workflow right before deploy, so the published demo can never drift from `data/codes.json`
the way a committed copy would — every newly coded character is live the next time the site
deploys.

Run it by hand before previewing locally:

    python3 site/tools/build_site_data.py

Reading Side A's data is fine from any side (the guard never blocks reads). Writing stays inside
`site/`, which is Side C's. This script must not write anywhere else.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DATA = ROOT / "data"
OUT = ROOT / "site" / "assets"


def shorten(code, rule):
    """Must stay identical to build_rime.py:36 — the demo is a lie if it disagrees with the IME."""
    if not rule:
        return code
    p = rule.get("params", {})
    mx, head, tail = p.get("max", 5), p.get("head", 4), p.get("tail", 1)
    if len(code) <= mx:
        return code
    return code[:head] + (code[-tail:] if tail else "")


def load(name):
    path = DATA / name
    if not path.exists():
        sys.exit(f"missing {path} — run this from a full checkout")
    return json.loads(path.read_text("utf-8"))


GRAPHICS_URL = "https://raw.githubusercontent.com/skishore/makemeahanzi/master/graphics.txt"
CACHE = ROOT / "site" / ".cache"


def _graphics_path():
    """找 makemeahanzi 的筆畫輪廓，找不到就下載到 site/.cache/（不寫 data/，那是 Side A 的）。

    優先用 data/graphics.txt（Side A 跑過 fetch_data.py 的話就在），因為那是同一份資料，
    沒必要在同一台機器上放兩份 29MB。CI 上是全新 checkout，一定是走下載那條路。
    """
    local = DATA / "graphics.txt"
    if local.exists():
        return local
    CACHE.mkdir(parents=True, exist_ok=True)
    cached = CACHE / "graphics.txt"
    if cached.exists() and cached.stat().st_size > 1_000_000:
        return cached
    import urllib.request
    print(f"  下載 graphics.txt（約 29MB）…")
    with urllib.request.urlopen(GRAPHICS_URL, timeout=300) as r:
        cached.write_bytes(r.read())
    return cached


def build_glyphs(chars):
    """把字根表要用到的字的**筆畫輪廓**抽出來，寫成 site/assets/glyphs.json。

    這是讓〈字根表〉能像標註工具那樣畫出字根本身的資料：每個字一組 SVG path，
    網站把屬於該字根的筆畫塗深、其餘塗淺（跟 editor.html 的 glyphSvg 同一套做法）。
    只取 strokes，不取 medians —— medians 是形狀比對用的，畫圖用不到，佔一半體積。

    ⚠️ 授權：這份資料源自 makemeahanzi，其 graphics.txt 依 **Arphic Public License**
    散布（該授權允許再散布與格式轉換，條件是隨附授權全文、註明改了什麼，並以同樣
    條款提供）。所以：
      - site/ARPHICPL.txt 是授權全文，必須跟著網站一起發佈，不要刪。
      - 下面的 note 欄就是「註明改了什麼」，也不要拿掉。
    Wilson 於 2026-08-17 決定接受這個義務，以換取字根表能真的畫出字根。

    抓不到資料時回傳 None，網站會自動退回純文字版（「取自『名』第 1–3 筆」），
    不會因為沒網路就整頁壞掉。
    """
    try:
        path = _graphics_path()
    except Exception as e:                      # 沒網路、GitHub 掛了、逾時
        print(f"  ⚠️ 拿不到 graphics.txt（{e}）—— 字根表退回純文字版")
        return None

    want = set(chars)
    out = {}
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            try:
                o = json.loads(line)
            except ValueError:
                continue
            c = o.get("character")
            if c in want and o.get("strokes"):
                out[c] = o["strokes"]

    payload = {
        "note": "generated by site/tools/build_site_data.py — do not edit",
        "source": "makemeahanzi (https://github.com/skishore/makemeahanzi) graphics.txt",
        "license": "Arphic Public License — 全文見 ARPHICPL.txt，隨網站一併發佈",
        "modifications": (
            "自 graphics.txt 取出本站用得到的字，只保留 strokes 欄（捨棄 medians／"
            "character 等其他欄位），並轉存為單一 JSON 物件。未修改任何筆畫路徑本身。"
            "變更日期 2026-08-17。"
        ),
        "glyphs": out,
    }
    (OUT / "glyphs.json").write_text(
        json.dumps(payload, ensure_ascii=False, separators=(",", ":")), "utf-8")
    return len(out)


def build_similar():
    """相近字形辨析：全部來自 site/content/similar.md，Wilson 手寫。

    資料裡沒有這種東西 —— 「哪兩個形狀容易認錯」是取碼的人腦袋裡的知識，zigen.json
    只知道兩個形狀不一樣（meta.distinct），不知道它們**像**。所以這一節不產生內容，
    只負責把手寫的檔案讀進來。檔案不存在或全空就回傳空 list，那一節整段不出現。

    格式（詳見 similar.md 檔頭）：
        ## 標題
        - 形 | 字母 | 例字 | 特徵
        > 整組說明
    """
    path = ROOT / "site" / "content" / "similar.md"
    if not path.exists():
        return []

    text = path.read_text("utf-8")
    # <!-- --> 之間是候選清單，不要當成內容
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    # ``` 圍起來的是格式說明本身（檔頭那段範例），不是資料 —— 不擋掉的話
    # 範例裡的「## 標題（隨便寫…）」會變成網站上真的一組辨析
    text = re.sub(r"^```.*?^```", "", text, flags=re.S | re.M)

    groups, cur = [], None
    for raw in text.splitlines():
        line = raw.strip()
        # Wilson 會很自然地寫 **粗體**；這裡不做 markdown，把星號去掉就好
        line = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
        if line.startswith("## "):
            if cur and cur["items"]:
                groups.append(cur)
            cur = {"title": line[3:].strip(), "items": [], "note": ""}
        elif line.startswith("- ") and cur is not None:
            parts = [p.strip() for p in line[2:].split("|")]
            if len(parts) < 4:
                continue                      # 欄位不夠就跳過，不要半條爛資料上線
            shape, letter, ex, trait = parts[0], parts[1], parts[2], " ".join(parts[3:])
            if shape == "？" or not letter:
                continue                      # 還沒填的候選
            cur["items"].append({
                "shape": shape,
                "letter": letter,
                "ex": [c for c in ex.split() if c],
                "trait": trait,
            })
        elif line.startswith(">") and cur is not None:
            cur["note"] = (cur["note"] + " " + line[1:].strip()).strip()

    if cur and cur["items"]:
        groups.append(cur)
    return groups


def build_zigen(zigen, codes, rank, far):
    """字根表：把 zigen.json 攤成網站要的形狀。

    ⚠️ 純文字版，刻意不畫字根。一個字根存的是「某個字的第幾筆到第幾筆」
    （glyph = {src, strokes}），筆畫幾何在 data/graphics.txt（makemeahanzi）裡，
    而那個檔 **gitignore、不隨本專案散布**，CI 上也不存在。所以這裡只輸出文字：
    取形意圖（desc）、取自哪個字的第幾筆、以及例字。要畫出字根、在例字上高亮，
    得先解決字形資料的授權與取得——那是另一個決定，不要偷偷在這裡引入相依。

    例字（seen）依字頻排序後截斷：常用字排前面，學的人才認得出來。
    """
    # 筆畫總數只能從 codes.json 的 segments 反推（union 出來的最大索引 + 1）。
    # 有了它才能分辨「整個字」和「字的前幾筆」——沒有 graphics.txt 就只有這條路。
    nstrokes = {}
    for ch, rec in codes.items():
        mx = -1
        for seg in rec.get("segments") or []:
            for s in seg.get("strokes") or []:
                if s > mx:
                    mx = s
        if mx >= 0:
            nstrokes[ch] = mx + 1

    def span(src, strokes):
        """人看得懂的說法：整個「名」字 / 名 的第 1–3 筆 / 名 的第 1、3、4 筆"""
        if not strokes:
            return ""
        ss = sorted(strokes)
        total = nstrokes.get(src)
        if total and len(ss) == total and ss == list(range(total)):
            return "whole"
        if ss == list(range(ss[0], ss[-1] + 1)):
            return f"{ss[0] + 1}–{ss[-1] + 1}" if len(ss) > 1 else f"{ss[0] + 1}"
        return "、".join(str(s + 1) for s in ss)

    letters, n_shapes, n_nodesc = [], 0, 0
    for L in zigen.get("letters", []):
        groups = []
        for it in L.get("intentions", []):
            shapes = []
            for sh in it.get("shapes", []):
                g = sh.get("glyph") or {}
                src = g.get("src") or sh.get("ex") or ""
                seen = [c for c in (sh.get("seen") or []) if c in codes]
                seen.sort(key=lambda c: rank.get(c, far))
                shapes.append({
                    "src": src,
                    # 原始筆畫索引：畫字根要用它去 glyphs.json 挑出哪幾筆塗深。
                    # span 是給人看的文字（「第 1–3 筆」），沒有字形資料時的退路。
                    "st": g.get("strokes") or [],
                    "span": span(src, g.get("strokes") or []),
                    "count": sh.get("count", 0),
                    "seen": seen,
                })
                n_shapes += 1
            if not shapes:
                continue
            desc = (it.get("desc") or "").strip()
            if not desc:
                n_nodesc += 1
            # 原形先、衍生後（倉頡的輔助字形表也是這個順序）。整個字構成的字根就是原形，
            # 先看到「日」再看到「提 的第 4–7 筆」才讀得懂；純照 count 排會把衍生形頂到最前面。
            shapes.sort(key=lambda s: (s["span"] != "whole", -s["count"]))
            groups.append({"desc": desc, "tier": it.get("tier") or "primary",
                           "shapes": shapes})
        letters.append({"letter": L.get("letter", ""), "groups": groups})

    return {
        "note": "generated by site/tools/build_site_data.py — do not edit",
        "tiers": (zigen.get("meta") or {}).get("tiers") or {},
        "shapes": n_shapes,
        "no_desc": n_nodesc,
        "letters": letters,
    }


def main():
    codes = load("codes.json")
    rules = load("rules.json")
    freq_order = load("freq.json").get("order", [])
    t2s_raw = load("opencc.json").get("t2s", {})

    max_rule = next((r for r in rules.get("rules", [])
                     if r["id"] == "max_code_length" and r.get("enabled")), None)

    # 字頻決定候選順序，跟 IME 的候選列一致；沒進字頻表的字排最後、彼此照碼表順序。
    rank = {c: i for i, c in enumerate(freq_order)}
    far = len(rank) + 1

    table = {}          # code(lower) -> [chars]

    def add(code, ch):
        if not code:
            return
        bucket = table.setdefault(code.lower(), [])
        if ch not in bucket:
            bucket.append(ch)

    for ch, rec in codes.items():
        full = rec.get("code")
        if not full:
            continue
        # display：makemeahanzi 偶爾把字形畫成別的通行體（為 → 爲），碼表輸出的是那個字形。
        out = rec.get("display") or ch
        add(shorten(full, max_rule), out)       # 主碼：實際要按的
        add(full, out)                          # 完整碼：拆完每一碼也一律接受
        for alt in rec.get("alts", []):         # 兼容碼：手動收的另一條路（連它的完整碼）
            ac = alt.get("code")
            if ac:
                add(shorten(ac, max_rule), out)
                add(ac, out)

    for bucket in table.values():
        bucket.sort(key=lambda c: rank.get(c, far))

    # 約定簡碼：60 個手挑的常用字。這是網站要示範的核心設計，所以一起輸出。
    short, short_rev = {}, {}
    sc = next((r for r in rules.get("rules", []) if r["id"] == "short_code"), None)
    if sc:
        for e in (sc.get("params", {}).get("entries") or sc.get("entries") or []):
            ch, s = e.get("c"), (e.get("short") or "").lower()
            if not ch or not s or ch not in codes:
                continue
            short.setdefault(s, ch)             # 撞碼時第一個贏，與 rules 頁預覽一致
            short_rev.setdefault(ch, s)

    # 官方字表覆蓋率：網站首頁的數字由這裡算，不手抄。手抄的數字每次取碼都會過期，
    # 而過期的進度數字在對外網站上比沒有數字更糟。
    stats = {"chars": len(codes)}
    for sid, label, fname in [("tw4808", "教育部常用國字", "tw_common_4808.txt"),
                              ("gb2312", "GB 2312", "gb2312.txt")]:
        path = DATA / "standards" / fname
        if not path.exists():
            continue
        chars = {c for line in path.read_text("utf-8").splitlines()
                 if not line.startswith("#") for c in line.strip()}
        done = len(chars & set(codes))
        stats[sid] = {"label": label, "done": done, "total": len(chars),
                      "pct": round(done * 100 / len(chars), 1)}

    # 重碼率：首 2000 常用字裡，有多少字跟別的字共用同一個主碼。這是對外會被引用的數字，
    # 所以定義寫死在這裡、每次重算 —— 「涉及重碼的字 ÷ 2000」，跟文案講的是同一件事。
    top = [c for c in freq_order if c in codes][:2000]
    groups = {}
    for ch in top:
        groups.setdefault(shorten(codes[ch]["code"], max_rule), []).append(ch)
    clashed = sum(len(v) for v in groups.values() if len(v) > 1)
    if top:
        stats["clash"] = {"pool": len(top), "chars": clashed,
                          "pct": round(clashed * 100 / len(top), 1)}

    dict_out = {
        "note": "generated by site/tools/build_site_data.py — do not edit",
        "chars": len(codes),
        "stats": stats,
        "codes": {k: "".join(v) for k, v in sorted(table.items())},
        "short": short,
        "short_rev": short_rev,
        "short_enabled": bool(sc and sc.get("enabled")),
    }

    # 值是候選陣列，取第一個（標準簡化字）；51 個多候選字的其餘寫法用不到。
    t2s = {k: (v[0] if isinstance(v, list) else v) for k, v in t2s_raw.items()}
    t2s = {k: v for k, v in t2s.items() if k != v}

    zigen_raw = load("zigen.json")
    zg = build_zigen(zigen_raw, codes, rank, far)
    zg["similar"] = build_similar()

    # 字根表要畫出字根本身，需要這些字的筆畫輪廓。先只收字根的**來源字**（含 alts）：
    # 695 字約 1.6MB。例字的高亮還要再 2000 字／+4.5MB，等這一版看過再決定。
    glyph_chars = set()
    for L in zigen_raw.get("letters", []):
        for it in L.get("intentions", []):
            for sh in it.get("shapes", []):
                g = sh.get("glyph") or {}
                if g.get("src"):
                    glyph_chars.add(g["src"])
                for a in sh.get("alts") or []:
                    if a.get("src"):
                        glyph_chars.add(a["src"])
    n_glyph = build_glyphs(glyph_chars)

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "dict.json").write_text(
        json.dumps(dict_out, ensure_ascii=False, separators=(",", ":")), "utf-8")
    (OUT / "t2s.json").write_text(
        json.dumps(t2s, ensure_ascii=False, separators=(",", ":")), "utf-8")
    (OUT / "zigen.json").write_text(
        json.dumps(zg, ensure_ascii=False, separators=(",", ":")), "utf-8")

    print(f"dict.json  {len(dict_out['codes'])} 碼 / {len(codes)} 字 / {len(short)} 簡碼")
    print(f"t2s.json   {len(t2s)} 組繁簡對照")
    if n_glyph:
        kb = (OUT / "glyphs.json").stat().st_size / 1024
        print(f"glyphs.json {n_glyph} 字的筆畫輪廓 / {kb:.0f} KB  （Arphic PL，見 site/ARPHICPL.txt）")
    print(f"zigen.json {zg['shapes']} 個字根 / {len(zg['letters'])} 個字母"
          + f" / {len(zg['similar'])} 組相近字形辨析"
          + (f"  ⚠️ {zg['no_desc']} 組還沒寫取形意圖" if zg["no_desc"] else ""))


if __name__ == "__main__":
    main()
